name = "cf yasir"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
 PROXYIP = "188.114.99.31:1018"
UUID = "52d03083-8ef7-415d-bb86-65457830a195"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
